"use client";

import { useState, useCallback } from 'react';
import { Language, Translations } from '../types';

export const translations: Translations = {
  uz: {
    nav_about: "Biz haqimizda",
    nav_products: "Mahsulotlar",
    nav_process: "Ishlab chiqarish",
    nav_cert: "Sertifikatlar",
    nav_projects: "Loyihalar",
    nav_contact: "Bog‘lanish",
    hero_tagline: "50 yillik tajriba va yuqori sifatli temir-beton mahsulotlari.<br>Mamlakat energetikasi uchun ishonchli poydevor.",
    hero_btn: "Hamkorlik boshlang",
    about_title: "Biz haqimizda",
    about_subtitle: "Yarim asrdan ortiq tarix va ishonchli hamkorlik",
    about_text1: '<span class="highlight">Zavodimiz 50 yildan ziyod</span> vaqt mobaynida mamlakat energetikasi uchun xizmat qilmoqda. <strong>2021 yilda</strong> Aksiyadorlik jamiyatiga aylandik, bu yangi investitsiyalar va ishlab chiqarishni modernizatsiya qilish imkonini berdi.',
    about_text2: "Bizning eng katta boyligimiz — ko‘p yillik tajribaga ega mutaxassislarimiz: yuqori malakali muhandislar, sifat nazorati inspektorlari va mas'uliyatli ishchi-xodimlar.",
    stat1: "Yillik tajriba",
    stat2: "Mutaxassislar",
    stat3: "Muvaffaqiyatli loyiha",
    about_image: "Zavod ko‘rinishi",
    team_title: "Bizning jamoa va texnika",
    team_subtitle: "Kuchli kadrlar va zamonaviy uskunalar",
    card1_title: "Ahil jamoa",
    card1_desc: "Yuqori malakali muhandislar, inspektorlar va ishchilar",
    card2_title: "Zamonaviy uskunalar",
    card2_desc: "Yuqori quvvatli beton qorishtirish, vibropress va qoliplash mashinalari",
    card3_title: "Kuchli avtopark",
    card3_desc: "Katta hajmdagi yuk ko‘tarish kranlari va logistika vositalari",
    products_title: "Mahsulotlar",
    products_subtitle: "Energetika va sanoat uchun temir-beton buyumlar",
    cat_f: "F-Seriyasi Fundamentlari",
    cat_poles: "Tayanch va ustunlar (Stalbalar)",
    poles_note: "Kuchli mexanik ta’sirlar va shamolga yuqori darajada bardoshli.",
    cat_other: "Lotoklar, plitalar va maxsus buyumlar",
    process_title: "Ishlab chiqarish bosqichlari",
    process_subtitle: "Sifatni har bir bosqichda nazorat qilamiz",
    step1_title: "Xomashyo nazorati",
    step1_desc: "Armatura karkaslari tayyorlash va materiallarni tekshirish",
    step2_title: "Beton tayyorlash",
    step2_desc: "Yuqori markali betonni vibropresslash orqali zichlash",
    step3_title: "Laboratoriya sinovi",
    step3_desc: "Qat’iy sifat nazorati va standartlarga muvofiqlik",
    step4_title: "Yetkazib berish",
    step4_desc: "Buyurtmachiga o‘z vaqtida va xavfsiz yetkazish",
    cert_title: "Xalqaro standartlar va sertifikatlar",
    cert_subtitle: "Mahsulotlarimiz jahon talablariga javob beradi",
    cert1: "ISO 9001 — Sifat menejmenti",
    cert2: "Ekologik xavfsizlik",
    cert3: "Xalqaro eksport standartlari",
    projects_title: "Bizning yirik loyihalarimiz",
    projects_subtitle: "O‘zbekiston va mintaqa bo‘ylab strategik obyektlar",
    projects_placeholder: "Yirik loyihalardan ko‘rinishlar",
    projects_note: "Yuzlab muvaffaqiyatli topshirilgan loyihalar — ishonchlilik kafolati",
    why_title: "Nima uchun aynan bizni tanlashadi?",
    why_subtitle: "Bizning afzalliklarimiz",
    why1_title: "50 yillik tajriba",
    why1_desc: "Bozorda barqaror va ishonchli faoliyat",
    why2_title: "ISO 9001 sifat",
    why2_desc: "Qat’iy laboratoriya nazorati va standartlar",
    why3_title: "Tezkor logistika",
    why3_desc: "O‘z vaqtida va xavfsiz yetkazib berish",
    clients_title: "Bizning mijozlar va hamkorlar",
    clients_subtitle: "Yillar davomida ishonchli hamkorlik",
    client1: "O‘zbekiston energetika kompaniyalari",
    client2: "Yirik qurilish trestlari",
    client3: "Pudrat tashkilotlari",
    client4: "Sanoat obyektlari",
    contact_title: "Bog‘lanish va manzil",
    contact_subtitle: "Biz bilan bog‘laning, hamkorlikka tayyormiz!",
    address: "O‘zbekiston Respublikasi",
    footer_motto: "Kelajak sari ishonchli qadam",
    footer_copy: "© 2026 ENERGOQURILISHMAHSULOT. Barcha huquqlar himoyalangan.",
    footer_motto2: "Kelajak sari ishonchli qadam.",
    form_name: "Ismingiz",
    form_email: "E-pochta",
    form_phone: "Telefon",
    form_message: "Xabar yoki so‘rov",
    form_submit: "Yuborish",
    cert_doc_title: "Rasmiy hujjatlar",
    cert_doc1_title: "Davlat ro'yxatidan o'tkazish guvohnomasi",
    cert_doc1_desc: "\"ENERGOQURILISHMAXSULOT\" MCHJ yuridik shaxs sifatida davlat ro'yxatidan o'tganligi to'g'risidagi rasmiy guvohnoma",
    cert_doc2_title: "Sertifikat sootvetstviya",
    cert_doc2_desc: "Mahsulotlarimizning O'zbekiston Respublikasi Milliy sertifikatlash tizimi talablariga muvofiqligini tasdiqlovchi sertifikat (ilova bilan)",
    cert_doc_view: "Ko'rish",
    cert_doc_download: "Yuklab olish",
  },
  ru: {
    nav_about: "О нас",
    nav_products: "Продукция",
    nav_process: "Производство",
    nav_cert: "Сертификаты",
    nav_projects: "Проекты",
    nav_contact: "Контакты",
    hero_tagline: "50-летний опыт и высококачественные железобетонные изделия.<br>Надёжный фундамент для энергетики страны.",
    hero_btn: "Начать сотрудничество",
    about_title: "О нас",
    about_subtitle: "Более полувековой истории и надёжного партнёрства",
    about_text1: '<span class="highlight">Наш завод более 50 лет</span> служит энергетике страны. В <strong>2021 году</strong> мы стали акционерным обществом, что позволило привлечь новые инвестиции и модернизировать производство.',
    about_text2: "Наше главное богатство — это высококвалифицированные специалисты с многолетним опытом: инженеры, инспекторы по качеству и ответственные рабочие.",
    stat1: "Лет опыта",
    stat2: "Специалистов",
    stat3: "Успешных проектов",
    about_image: "Вид завода",
    team_title: "Наша команда и техника",
    team_subtitle: "Квалифицированные кадры и современное оборудование",
    card1_title: "Дружный коллектив",
    card1_desc: "Высококвалифицированные инженеры, инспекторы и рабочие",
    card2_title: "Современное оборудование",
    card2_desc: "Мощные бетоносмесители, вибропрессы и формовочные машины",
    card3_title: "Мощный автопарк",
    card3_desc: "Крупнотоннажные краны и логистические средства",
    products_title: "Продукция",
    products_subtitle: "Железобетонные изделия для энергетики и промышленности",
    cat_f: "Фундаменты серии F",
    cat_poles: "Опоры и стойки (Стальба)",
    poles_note: "Высокая устойчивость к механическим воздействиям и ветру.",
    cat_other: "Лотки, плиты и специзделия",
    process_title: "Этапы производства",
    process_subtitle: "Контроль качества на каждом этапе",
    step1_title: "Контроль сырья",
    step1_desc: "Подготовка арматурных каркасов и проверка материалов",
    step2_title: "Приготовление бетона",
    step2_desc: "Уплотнение высокомарочного бетона вибропрессованием",
    step3_title: "Лабораторные испытания",
    step3_desc: "Строгий контроль качества и соответствие стандартам",
    step4_title: "Доставка",
    step4_desc: "Своевременная и безопасная доставка заказчику",
    cert_title: "Международные стандарты и сертификаты",
    cert_subtitle: "Наша продукция соответствует мировым требованиям",
    cert1: "ISO 9001 — Система менеджмента качества",
    cert2: "Экологическая безопасность",
    cert3: "Международные экспортные стандарты",
    projects_title: "Наши крупные проекты",
    projects_subtitle: "Стратегические объекты по всему Узбекистану и региону",
    projects_placeholder: "Вид крупных проектов",
    projects_note: "Сотни успешно реализованных проектов — гарантия нашей надёжности",
    why_title: "Почему выбирают нас?",
    why_subtitle: "Наши преимущества",
    why1_title: "50-летний опыт",
    why1_desc: "Стабильная и надёжная деятельность на рынке",
    why2_title: "Качество ISO 9001",
    why2_desc: "Строгий лабораторный контроль и стандарты",
    why3_title: "Быстрая логистика",
    why3_desc: "Своевременная и безопасная доставка",
    clients_title: "Наши клиенты и партнёры",
    clients_subtitle: "Надёжное сотрудничество на протяжении многих лет",
    client1: "Энергетические компании Узбекистана",
    client2: "Крупные строительные тресты",
    client3: "Подрядные организации",
    client4: "Промышленные объекты",
    contact_title: "Контакты и адрес",
    contact_subtitle: "Свяжитесь с нами, мы готовы к сотрудничеству!",
    address: "Республика Узбекистан",
    footer_motto: "Надёжный шаг в будущее",
    footer_copy: "© 2026 ЭНЕРГОКУРИЛИШМАХСУЛОТ. Все права защищены.",
    footer_motto2: "Надёжный шаг в будущее.",
    form_name: "Ваше имя",
    form_email: "Эл. почта",
    form_phone: "Телефон",
    form_message: "Сообщение или запрос",
    form_submit: "Отправить",
    cert_doc_title: "Официальные документы",
    cert_doc1_title: "Свидетельство о государственной регистрации",
    cert_doc1_desc: "Официальное свидетельство о государственной регистрации юридического лица \"ENERGOQURILISHMAXSULOT\" МЧЖ",
    cert_doc2_title: "Сертификат соответствия",
    cert_doc2_desc: "Сертификат, подтверждающий соответствие нашей продукции требованиям Национальной системы сертификации Республики Узбекистан (с приложением)",
    cert_doc_view: "Просмотреть",
    cert_doc_download: "Скачать",
  },
  en: {
    nav_about: "About Us",
    nav_products: "Products",
    nav_process: "Production",
    nav_cert: "Certificates",
    nav_projects: "Projects",
    nav_contact: "Contact",
    hero_tagline: "50 years of experience and high-quality reinforced concrete products.<br>A reliable foundation for the country's energy sector.",
    hero_btn: "Start Cooperation",
    about_title: "About Us",
    about_subtitle: "Over half a century of history and reliable partnership",
    about_text1: '<span class="highlight">Our plant has been serving the country\'s energy sector for over 50 years.</span> In <strong>2021</strong> we became a joint-stock company, which enabled new investments and modernization of production.',
    about_text2: "Our greatest asset is our highly skilled specialists with many years of experience: engineers, quality control inspectors and dedicated workers.",
    stat1: "Years of experience",
    stat2: "Specialists",
    stat3: "Successful projects",
    about_image: "Factory view",
    team_title: "Our team and equipment",
    team_subtitle: "Skilled personnel and modern machinery",
    card1_title: "Friendly team",
    card1_desc: "Highly qualified engineers, inspectors and workers",
    card2_title: "Modern equipment",
    card2_desc: "High-power concrete mixers, vibropress and molding machines",
    card3_title: "Strong vehicle fleet",
    card3_desc: "Large-capacity cranes and logistics vehicles",
    products_title: "Products",
    products_subtitle: "Reinforced concrete products for energy and industry",
    cat_f: "F-Series Foundations",
    cat_poles: "Supports and poles (Stalba)",
    poles_note: "High resistance to mechanical stress and wind.",
    cat_other: "Trays, slabs and special products",
    process_title: "Production stages",
    process_subtitle: "Quality control at every stage",
    step1_title: "Raw material control",
    step1_desc: "Preparation of reinforcement frames and material inspection",
    step2_title: "Concrete preparation",
    step2_desc: "Compaction of high-grade concrete by vibropressing",
    step3_title: "Laboratory testing",
    step3_desc: "Strict quality control and compliance with standards",
    step4_title: "Delivery",
    step4_desc: "Timely and safe delivery to the customer",
    cert_title: "International standards and certificates",
    cert_subtitle: "Our products meet global requirements",
    cert1: "ISO 9001 — Quality management system",
    cert2: "Environmental safety",
    cert3: "International export standards",
    projects_title: "Our major projects",
    projects_subtitle: "Strategic facilities across Uzbekistan and the region",
    projects_placeholder: "Views of major projects",
    projects_note: "Hundreds of successfully completed projects — a guarantee of our reliability",
    why_title: "Why choose us?",
    why_subtitle: "Our advantages",
    why1_title: "50 years of experience",
    why1_desc: "Stable and reliable market presence",
    why2_title: "ISO 9001 quality",
    why2_desc: "Strict laboratory control and standards",
    why3_title: "Fast logistics",
    why3_desc: "Timely and safe delivery",
    clients_title: "Our clients and partners",
    clients_subtitle: "Reliable cooperation over the years",
    client1: "Uzbekistan energy companies",
    client2: "Large construction trusts",
    client3: "Contracting organizations",
    client4: "Industrial facilities",
    contact_title: "Contact and address",
    contact_subtitle: "Get in touch, we are ready to cooperate!",
    address: "Republic of Uzbekistan",
    footer_motto: "A reliable step towards the future",
    footer_copy: "© 2026 ENERGOQURILISHMAHSULOT. All rights reserved.",
    footer_motto2: "A reliable step towards the future.",
    form_name: "Your name",
    form_email: "Email",
    form_phone: "Phone",
    form_message: "Message or request",
    form_submit: "Send",
    cert_doc_title: "Official documents",
    cert_doc1_title: "State registration certificate",
    cert_doc1_desc: "Official certificate confirming the state registration of \"ENERGOQURILISHMAXSULOT\" LLC as a legal entity",
    cert_doc2_title: "Certificate of conformity",
    cert_doc2_desc: "Certificate confirming that our products meet the requirements of the National Certification System of the Republic of Uzbekistan (with appendix)",
    cert_doc_view: "View",
    cert_doc_download: "Download",
  }
};

export function useLanguage(initialLang: Language = 'uz') {
  const [currentLang, setCurrentLang] = useState<Language>(initialLang);

  const setLanguage = useCallback((lang: Language) => {
    setCurrentLang(lang);
  }, []);

  const t = useCallback(
    (key: string) => {
      return translations[currentLang][key] || key;
    },
    [currentLang]
  );

  return { currentLang, setLanguage, t };
}
